version: '3'

services:
  reproducing-churches-database: 
    image: postgres:latest 
    container_name: reproducing-churches-database 
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - reproducing-churches-network

  web-project:
    hostname: "${HOSTNAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/platform
    command: >
      bash -c "
        python manage.py runserver ${HOSTNAME}:${PORT}
      "
    volumes:
      - ./platform/:/usr/src/platform
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
    env_file:
      .env
    depends_on:
      - reproducing-churches-database
    networks:
      - reproducing-churches-network

networks:
  reproducing-churches-network:
    external: true
