version: '3'

services:
  ever-desk-database: 
    image: postgres:latest 
    container_name: ever-desk-database 
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - ever-desk-network

  web-project:
    hostname: "${HOSTNAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/everdesk
    command: >
      bash -c "
        python manage.py runserver ${HOSTNAME}:${PORT}
      "
    volumes:
      - ./ever_desk/:/usr/src/everdesk
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
    env_file:
      .env
    depends_on:
      - ever-desk-database
    networks:
      - ever-desk-network

networks:
    ever-desk-network:
        external: true
